set nu
set si shiftwidth=2
set backspace=2
set ruler
set hlsearch
set showmode
set tabstop=2
set expandtab
"set textwidth=72
set wrap
set softtabstop=2
set autoread
set autowriteall
au FocusGained,BufEnter * :silent! !
au FocusLost,WinLeave * :silent! w
"
"color configuration
color ron
highlight Cursor guifg=red guibg=yellow
highlight iCursor guifg=red guibg=yellow
set t_md=
"
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm'\"")|else|exe "norm $"|endif|endif
"
"======================================
 
" Vim Fortran Configuration
" http://blog.163.com/wujiaxing009@126/blog/static/71988399201243064711872/
filetype plugin on
filetype plugin indent on
"set tabstop=2
"set cindent shiftwidth=2
"set autoindent shiftwidth=2

 let fortran_fold=0
 set foldmethod=syntax
 set foldcolumn=4
 set nofoldenable

"======================================

" Vim Latex-Suite Configuration

"http://vim-latex.sourceforge.net/documentation/latex-suite/recommended-settings.html

" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a singe file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'

" this is mostly a matter of taste. but LaTeX looks good with just a bit
" of indentation.
set sw=2
" TIP: if you write your \label's as \label{fig:something}, then if you
" type in \ref{fig: and press <C-n> you will automatically cycle through
" all the figure labels. Very useful!
set iskeyword+=:

"https://tex.stackexchange.com/questions/285301/ignore-errors-in-environments-in-latex-suite-in-vim

au BufRead,BufNewFile *.tex,*.sty,*.cls set filetype=tex
au FileType tex syntax on
au filetype tex syntax region texZone start='\\begin{lstlisting}' end='\\end{lstlisting}'
au filetype tex syntax region texZone start='\\texttt{' end='}'
au filetype tex syntax region texZone start='\\verb!' end='!'

"======================================
"
" Paste mode

  noremap <silent><Leader>p :call TogglePaste()<CR>
  function TogglePaste()
    if &paste
      echo "No paste mode"
      set nopaste
    else
      echo "Paste mode"
      set paste
    endif
  endfunction

"======================================
"
" Move by displayed line
"http://vim.wikia.com/wiki/Move_cursor_by_display_lines_when_wrapping

"noremap <silent> <Leader>w :call ToggleWrap()<CR>
"function ToggleWrap()
"  if &wrap
"    echo "Wrap OFF"
"    setlocal nowrap
"    set virtualedit=all
"    silent! nunmap <buffer> <Up>
"    silent! nunmap <buffer> <Down>
"    silent! nunmap <buffer> <Home>
"    silent! nunmap <buffer> <End>
"    silent! iunmap <buffer> <Up>
"    silent! iunmap <buffer> <Down>
"    silent! iunmap <buffer> <Home>
"    silent! iunmap <buffer> <End>
"  else
"    echo "Wrap ON"
"   setlocal wrap linebreak nolist
"    set virtualedit=
"    setlocal display+=lastline
    noremap  <buffer> <silent> <Up>   gk
    noremap  <buffer> <silent> <Down> gj
    noremap  <buffer> <silent> <Home> g<Home>
    noremap  <buffer> <silent> <End>  g<End>
    inoremap <buffer> <silent> <Up>   <C-o>gk
    inoremap <buffer> <silent> <Down> <C-o>gj
    inoremap <buffer> <silent> <Home> <C-o>g<Home>
    inoremap <buffer> <silent> <End>  <C-o>g<End>
"  endif
"endfunction

"======================================
"
"

"函数名:    OneKey_Compile_OneCFile
"参数：        无
"功能：        一键编译单个C源文件
"作者：        play
"版本：        v1.0
"修改历史：
"=======================================
function OneKey_Compile_OneCFile()

    exec "w"

    if ( expand("%:p:h") != getcwd() )
        echohl WarningMsg
    echo "Fail to make! This file is not in the current dir."
    echohl None
    return
    endif

    set makeprg=gfortran\ -g\ -o\ %<.out\ %\ -llapack\ -lblas

    execute "make"

    execute "copen"

endfunction

function OneKey_Execution_OneCFile()

    if ( expand("%:p:h") != getcwd() )
        echohl WarningMsg
    echo "Fail to make! This file is not in the current dir."
    echohl None
    return
    endif

    exec ":!./%<.out"

endfunction

function OneKey_Check_OneCFile()

    exec "w"

    if ( expand("%:p:h") != getcwd() )
        echohl WarningMsg
    echo "Fail to make! This file is not in the current dir."
    echohl None
    return
    endif

    set makeprg=ftnchek\ -f77\ %

    execute "make"

    execute "copen"

endfunction

function MyCode()

    exec "w"

endfunction

function OneKey_GfCompile_OneCFile()

    exec "w"

    if ( expand("%:p:h") != getcwd() )
        echohl WarningMsg
    echo "Fail to make! This file is not in the current dir."
    echohl None
    return
    endif

    set makeprg=gfortran\ -Wall\ -g\ -o\ %<.out\ %\ -llapack\ -lblas

    execute "make"

    execute "copen"

endfunction


nmap <F4> :call OneKey_GfCompile_OneCFile()<cr>
nmap <F5> :call OneKey_Compile_OneCFile()<cr>
nmap <F6> :call OneKey_Execution_OneCFile()<cr>
nmap <F7> :call OneKey_Check_OneCFile()<cr>
nmap <F10> :call MyCode()<cr>

   au FileType qf call AdjustWindowHeight(15,15)
   function! AdjustWindowHeight(minheight, maxheight)
       let l = 1
       let n_lines = 0
       let w_width = winwidth(0)
       while l <= line('$')
           " number to float for division
           let l_len = strlen(getline(l)) + 0.0
           let line_width = l_len/w_width
           let n_lines += float2nr(ceil(line_width))
           let l += 1
       endw
       exe max([min([n_lines, a:maxheight]), a:minheight]) . "wincmd _"
   endfunction
   " https://gist.github.com/juanpabloaj/5845848

